# Generated by Django 6.0 on 2026-07-01 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_contactmessage_is_replied_messagereply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_replied',
        ),
        migrations.DeleteModel(
            name='MessageReply',
        ),
    ]
