# Generated by Django 6.0 on 2026-07-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_contactmessage_is_replied_delete_messagereply'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='proficiency',
            field=models.IntegerField(default=75, help_text='Skill proficiency level from 0 to 100'),
        ),
    ]
